In [8]:
import pandas as pd
df = pd.read_csv('df_favorites.csv',sep=',')
df

        user_id  used_favorites      revenue    revenue_0    revenue_1
0        205105               1  1057.018919  1037.018919  1057.018919
1        187143               0  1061.578463  1061.578463  1071.578463
2        190405               0  1065.078049  1065.078049  1075.078049
3        190487               1   838.983047   818.983047   838.983047
4        191840               0  1130.772273  1130.772273  1140.772273
...         ...             ...          ...          ...          ...
113467   133400               0  1127.795337  1127.795337  1137.795337
113468   194216               0  1024.041881  1024.041881  1034.041881
113469   117322               0  1039.646623  1039.646623  1049.646623
113470   206937               0   902.660004   902.660004   912.660004
113471   140740               1  1103.792053  1083.792053  1103.792053

[113472 rows x 5 columns]

In [25]:
avg_revenue = df.groupby('used_favorites')['revenue'].mean().reset_index()
avg_revenue

   used_favorites      revenue
0               0   999.794012
1               1  1035.059637

In [23]:
from pandasql import sqldf

query = """
SELECT 
    used_favorites,
    AVG(revenue) as avg_revenue
FROM df
GROUP BY used_favorites
"""

sqldf(query)

   used_favorites  avg_revenue
0               0   999.794012
1               1  1035.059637

In [28]:
(df['revenue_1'] - df['revenue_0']).mean()

np.float64(12.973420755781161)

In [29]:
df[df['user_id']==198045]

        user_id  used_favorites   revenue  revenue_0  revenue_1
108781   198045               0  898.8356   898.8356   908.8356

In [32]:
df_ATT = df[df['used_favorites']==0]
df_ATT

        user_id  used_favorites      revenue    revenue_0    revenue_1
1        187143               0  1061.578463  1061.578463  1071.578463
2        190405               0  1065.078049  1065.078049  1075.078049
4        191840               0  1130.772273  1130.772273  1140.772273
5        119192               0  1003.790202  1003.790202  1013.790202
6        174539               0  1021.754296  1021.754296  1031.754296
...         ...             ...          ...          ...          ...
113465   138515               0   926.008931   926.008931   936.008931
113467   133400               0  1127.795337  1127.795337  1137.795337
113468   194216               0  1024.041881  1024.041881  1034.041881
113469   117322               0  1039.646623  1039.646623  1049.646623
113470   206937               0   902.660004   902.660004   912.660004

[79732 rows x 5 columns]

In [33]:
(df_ATT['revenue_1'] - df_ATT['revenue_0']).mean()

np.float64(10.0)

In [34]:
df

        user_id  used_favorites      revenue    revenue_0    revenue_1
0        205105               1  1057.018919  1037.018919  1057.018919
1        187143               0  1061.578463  1061.578463  1071.578463
2        190405               0  1065.078049  1065.078049  1075.078049
3        190487               1   838.983047   818.983047   838.983047
4        191840               0  1130.772273  1130.772273  1140.772273
...         ...             ...          ...          ...          ...
113467   133400               0  1127.795337  1127.795337  1137.795337
113468   194216               0  1024.041881  1024.041881  1034.041881
113469   117322               0  1039.646623  1039.646623  1049.646623
113470   206937               0   902.660004   902.660004   912.660004
113471   140740               1  1103.792053  1083.792053  1103.792053

[113472 rows x 5 columns]

In [38]:
df.groupby('used_favorites')['revenue_0'].mean().reset_index()

   used_favorites    revenue_0
0               0   999.794012
1               1  1015.059637

In [36]:
1015.059 - 999.794

15.264999999999986